In [1]:
import torch
import numpy as np

<h1> Initializing a Tensor </h1>

In [2]:
data = [[1,2], [3,4]]
x_data = torch.tensor(data)

In [3]:
x_data

tensor([[1, 2],
        [3, 4]])

In [4]:
type(x_data)

torch.Tensor

<h1>From a numpy array </h1>

In [5]:
numparray = np.array(data)
x_data = torch.from_numpy(numparray)

In [6]:
x_data

tensor([[1, 2],
        [3, 4]])

In [7]:
type(x_data)

torch.Tensor

<h1>From another Tensor</h1>

In [8]:
x_ones = torch.ones_like(x_data)

In [9]:
x_ones

tensor([[1, 1],
        [1, 1]])

In [10]:
x_rand = torch.rand_like(x_data, dtype = torch.float)
x_rand

tensor([[0.7122, 0.5225],
        [0.9063, 0.6349]])

In [11]:
shape = (2,3,) #tuple of tensor dimensions
rand_tensor = torch.rand(shape)
rand_tensor

tensor([[0.0825, 0.0762, 0.3228],
        [0.2774, 0.1603, 0.6299]])

In [12]:
one_tensor = torch.ones(shape)
one_tensor


tensor([[1., 1., 1.],
        [1., 1., 1.]])

<h1>Attributes of a Tensor </h1>


In [13]:
tensor = torch.rand(3,4)
print(tensor)
print()
print(f'tensor shape:{tensor.shape}')
print()
print(f'tensor device:{tensor.device}')
print()
print(f'tensor dtype:{tensor.dtype}')

tensor([[0.8521, 0.0778, 0.6381, 0.2499],
        [0.5865, 0.7928, 0.5715, 0.1043],
        [0.4336, 0.7521, 0.2584, 0.6088]])

tensor shape:torch.Size([3, 4])

tensor device:cpu

tensor dtype:torch.float32


<h1> Operations on Tensors </h1>

In [14]:
if torch.cuda.is_available():
    tensor = tensor.to('cuda')

In [15]:
print(f'first row of:{tensor[0]} ')
print(f'first column of: {tensor[:,0]}')
print(f'last column of: {tensor[...,-1]} ')

first row of:tensor([0.8521, 0.0778, 0.6381, 0.2499]) 
first column of: tensor([0.8521, 0.5865, 0.4336])
last column of: tensor([0.2499, 0.1043, 0.6088]) 


In [16]:
tensor[:,3] = 69
tensor

tensor([[ 0.8521,  0.0778,  0.6381, 69.0000],
        [ 0.5865,  0.7928,  0.5715, 69.0000],
        [ 0.4336,  0.7521,  0.2584, 69.0000]])

In [17]:
#Joining tensors 
t1 = torch.cat([tensor, tensor, tensor], dim = 1)
t1

tensor([[ 0.8521,  0.0778,  0.6381, 69.0000,  0.8521,  0.0778,  0.6381, 69.0000,
          0.8521,  0.0778,  0.6381, 69.0000],
        [ 0.5865,  0.7928,  0.5715, 69.0000,  0.5865,  0.7928,  0.5715, 69.0000,
          0.5865,  0.7928,  0.5715, 69.0000],
        [ 0.4336,  0.7521,  0.2584, 69.0000,  0.4336,  0.7521,  0.2584, 69.0000,
          0.4336,  0.7521,  0.2584, 69.0000]])

In [18]:
#arithmetic operations

<h1>Matrix Multiplication Between Two Tensors </h1>

In [22]:
y = t1@t1.T
y

tensor([[14286.4170, 14285.7773, 14284.7783],
        [14285.7773, 14286.8965, 14285.9941],
        [14284.7783, 14285.9941, 14285.4600]])

In [24]:
y2 = t1.matmul(t1.T)
y2

tensor([[14286.4170, 14285.7773, 14284.7783],
        [14285.7773, 14286.8965, 14285.9941],
        [14284.7783, 14285.9941, 14285.4600]])

In [26]:
y3 = torch.rand_like(t1)
torch.matmul(t1, t1.T, out = y3)
y3

<ipython-input-26-6ef1ffc71fc9>:2: UserWarning: An output with one or more elements was resized since it had shape [3, 12], which does not match the required output shape [3, 3].This behavior is deprecated, and in a future PyTorch release outputs will not be resized unless they have zero elements. You can explicitly reuse an out tensor t by resizing it, inplace, to zero elements with t.resize_(0). (Triggered internally at  /Users/distiller/project/conda/conda-bld/pytorch_1634272482218/work/aten/src/ATen/native/Resize.cpp:23.)
  torch.matmul(t1, t1.T, out = y3)


tensor([[14286.4170, 14285.7773, 14284.7783],
        [14285.7773, 14286.8965, 14285.9941],
        [14284.7783, 14285.9941, 14285.4600]])

<h1>Element-Wise Product</h1>

In [27]:
z1 = t1* t1
z1

tensor([[7.2601e-01, 6.0587e-03, 4.0714e-01, 4.7610e+03, 7.2601e-01, 6.0587e-03,
         4.0714e-01, 4.7610e+03, 7.2601e-01, 6.0587e-03, 4.0714e-01, 4.7610e+03],
        [3.4400e-01, 6.2847e-01, 3.2664e-01, 4.7610e+03, 3.4400e-01, 6.2847e-01,
         3.2664e-01, 4.7610e+03, 3.4400e-01, 6.2847e-01, 3.2664e-01, 4.7610e+03],
        [1.8798e-01, 5.6565e-01, 6.6784e-02, 4.7610e+03, 1.8798e-01, 5.6565e-01,
         6.6784e-02, 4.7610e+03, 1.8798e-01, 5.6565e-01, 6.6784e-02, 4.7610e+03]])

In [28]:
z2 = t1.mul(t1)
z2

tensor([[7.2601e-01, 6.0587e-03, 4.0714e-01, 4.7610e+03, 7.2601e-01, 6.0587e-03,
         4.0714e-01, 4.7610e+03, 7.2601e-01, 6.0587e-03, 4.0714e-01, 4.7610e+03],
        [3.4400e-01, 6.2847e-01, 3.2664e-01, 4.7610e+03, 3.4400e-01, 6.2847e-01,
         3.2664e-01, 4.7610e+03, 3.4400e-01, 6.2847e-01, 3.2664e-01, 4.7610e+03],
        [1.8798e-01, 5.6565e-01, 6.6784e-02, 4.7610e+03, 1.8798e-01, 5.6565e-01,
         6.6784e-02, 4.7610e+03, 1.8798e-01, 5.6565e-01, 6.6784e-02, 4.7610e+03]])

In [29]:
z3 = torch.rand_like(t1)
torch.mul(t1,t1, out=z3)
z3

tensor([[7.2601e-01, 6.0587e-03, 4.0714e-01, 4.7610e+03, 7.2601e-01, 6.0587e-03,
         4.0714e-01, 4.7610e+03, 7.2601e-01, 6.0587e-03, 4.0714e-01, 4.7610e+03],
        [3.4400e-01, 6.2847e-01, 3.2664e-01, 4.7610e+03, 3.4400e-01, 6.2847e-01,
         3.2664e-01, 4.7610e+03, 3.4400e-01, 6.2847e-01, 3.2664e-01, 4.7610e+03],
        [1.8798e-01, 5.6565e-01, 6.6784e-02, 4.7610e+03, 1.8798e-01, 5.6565e-01,
         6.6784e-02, 4.7610e+03, 1.8798e-01, 5.6565e-01, 6.6784e-02, 4.7610e+03]])

In [19]:
import torch
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets
from torchvision.transforms import ToTensor, Lambda, Compose
import matplotlib.pyplot as plt

In [31]:
agg = t1.sum()
agg

tensor(635.8886)

In [32]:
agg_item = agg.item()
print(agg_item, type(agg_item))

635.8886108398438 <class 'float'>


<h1>In place operations </h1>
<h2> Operations that store the result into the operand are called in-place. They are denoted by a _ suffix. For example: x.copy_(y), x.t_(), will change x.</h2>

In [34]:
print(t1, '/n')
t1.add_(5)
print(t1)

tensor([[ 0.8521,  0.0778,  0.6381, 69.0000,  0.8521,  0.0778,  0.6381, 69.0000,
          0.8521,  0.0778,  0.6381, 69.0000],
        [ 0.5865,  0.7928,  0.5715, 69.0000,  0.5865,  0.7928,  0.5715, 69.0000,
          0.5865,  0.7928,  0.5715, 69.0000],
        [ 0.4336,  0.7521,  0.2584, 69.0000,  0.4336,  0.7521,  0.2584, 69.0000,
          0.4336,  0.7521,  0.2584, 69.0000]]) /n
tensor([[ 5.8521,  5.0778,  5.6381, 74.0000,  5.8521,  5.0778,  5.6381, 74.0000,
          5.8521,  5.0778,  5.6381, 74.0000],
        [ 5.5865,  5.7928,  5.5715, 74.0000,  5.5865,  5.7928,  5.5715, 74.0000,
          5.5865,  5.7928,  5.5715, 74.0000],
        [ 5.4336,  5.7521,  5.2584, 74.0000,  5.4336,  5.7521,  5.2584, 74.0000,
          5.4336,  5.7521,  5.2584, 74.0000]])


<h1>Datasets and Data Loaders </h1>
<h3>Datasets stores the samples and their corresponding labels</h3>
<h3>Dataloader wraps an iterable around the Dataset </h3>

In [36]:
import torch
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets
from torchvision.transforms import ToTensor, Lambda, Compose
import matplotlib.pyplot as plt
from torch.utils.data import Dataset


In [38]:
training_data = datasets.FashionMNIST(
                root = 'data',
                train = True,
                download = True,
                transform = ToTensor())

  0%|          | 0/26421880 [00:00<?, ?it/s]

Extracting data/FashionMNIST/raw/train-images-idx3-ubyte.gz to data/FashionMNIST/raw



  0%|          | 0/29515 [00:00<?, ?it/s]

Extracting data/FashionMNIST/raw/train-labels-idx1-ubyte.gz to data/FashionMNIST/raw



  0%|          | 0/4422102 [00:00<?, ?it/s]

Extracting data/FashionMNIST/raw/t10k-images-idx3-ubyte.gz to data/FashionMNIST/raw



  0%|          | 0/5148 [00:00<?, ?it/s]

Extracting data/FashionMNIST/raw/t10k-labels-idx1-ubyte.gz to data/FashionMNIST/raw



In [41]:
test_data = datasets.FashionMNIST(
            root = 'data',
            train = False,
            download = True,
            transform = ToTensor()
            )

In [42]:
test_data

Dataset FashionMNIST
    Number of datapoints: 10000
    Root location: data
    Split: Test
    StandardTransform
Transform: ToTensor()

<h2>Iterating and Visualizing the Dataset</h2>

In [3]:
a = 1

In [4]:
a+3

4